#!/bin/bash

cd debian

dpkg-scanpackages --multiversion . > Packages
gzip -k -f Packages

apt-ftparchive release . > Release
gpg --default-key "andrew@rail5.org" -abs -o - Release > Release.gpg
gpg --default-key "andrew@rail5.org" --clearsign -o - Release > InRelease

cd ..
